// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDin4bB6GuxQLsoRQbmkZNQNEiuwCKuHhE',
    appId: '1:541208047442:web:27781cfed2bd961c16948b',
    messagingSenderId: '541208047442',
    projectId: 'ricemill-app-xyz8',
    authDomain: 'ricemill-app-xyz8.firebaseapp.com',
    storageBucket: 'ricemill-app-xyz8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-XD7wfDbkbwjlC3J9Sqh7n44wnwtM1oU',
    appId: '1:541208047442:android:466b987ca1563a8516948b',
    messagingSenderId: '541208047442',
    projectId: 'ricemill-app-xyz8',
    storageBucket: 'ricemill-app-xyz8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENl_hkB8KnxR0t5ZS0CNqxY2E8ZmKXnw',
    appId: '1:541208047442:ios:1b6a78542d306ce516948b',
    messagingSenderId: '541208047442',
    projectId: 'ricemill-app-xyz8',
    storageBucket: 'ricemill-app-xyz8.firebasestorage.app',
    iosBundleId: 'com.example.ricemillApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAENl_hkB8KnxR0t5ZS0CNqxY2E8ZmKXnw',
    appId: '1:541208047442:ios:1b6a78542d306ce516948b',
    messagingSenderId: '541208047442',
    projectId: 'ricemill-app-xyz8',
    storageBucket: 'ricemill-app-xyz8.firebasestorage.app',
    iosBundleId: 'com.example.ricemillApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDin4bB6GuxQLsoRQbmkZNQNEiuwCKuHhE',
    appId: '1:541208047442:web:661a0e3f5ffa905f16948b',
    messagingSenderId: '541208047442',
    projectId: 'ricemill-app-xyz8',
    authDomain: 'ricemill-app-xyz8.firebaseapp.com',
    storageBucket: 'ricemill-app-xyz8.firebasestorage.app',
  );
}
